source: .
include: [_pages]
destination: docs
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Collections

collections_dir: collections

collections:
    youtube_projects:
        class: youtube-projects
        output: true
        permalink: /youtube-projects/:title
    posts:
        class: posts
        output: true
        permalink: /posts/:title

sass:
    sass_dir: _sass
